DROP TABLE dbresprod.dbo.SEL_UPDATES;
DROP TABLE dbresprod.dbo.SEL_READINGS;
DROP TABLE dbresprod.dbo.SEL_ALARMS;
DROP TABLE dbresprod.dbo.SEL_REQUESTS;
DROP TABLE dbresprod.dbo.SEL_OUTPUTS;
DROP TABLE dbresprod.dbo.SEL_MEASURE_UNITS;
DROP TABLE dbresprod.dbo.SEL_TYPES;
DROP TABLE dbresprod.dbo.SEL_STATUSES;
DROP TABLE dbresprod.dbo.SEL_MODES;
DROP TABLE dbresprod.dbo.SEL_UNITS;
DROP TABLE dbresprod.dbo.SEL_SENSORS;
GO