/* Check if NETWORK exists, if not create it */
CREATE PROCEDURE PROC_GET_LOGGER_CIK(@cik INT)
AS
BEGIN
	SET NOCOUNT ON;
	IF EXISTS
	(
		SELECT cik
		FROM IGNITION.dbo.NOVUS_CIK
		WHERE cik = @cik
	)
	BEGIN
		PRINT('LOGGER CIK DOES NOT EXIST, SKIPPING...')
	END
END
GO

CREATE PROCEDURE PROC_GET_LOGGER_SN(@sn INT)
AS
BEGIN
	SET NOCOUNT ON;
	IF EXISTS
	(
		SELECT sn
		FROM IGNITION.dbo.NOVUS_SN
		WHERE sn = @sn
	)
	BEGIN
		PRINT('LOGGER SN DOES NOT EXIST, SKIPPING...')
	END
END
GO