DROP TABLE dbresprod.dbo.MONNIT_SENSOR_VOLTAGE;
DROP TABLE dbresprod.dbo.MONNIT_PENDING_CHANGES;
DROP TABLE dbresprod.dbo.MONNIT_BATTERY_STATUS;
DROP TABLE dbresprod.dbo.MONNIT_SIGNAL_STATUS;
DROP TABLE dbresprod.dbo.MONNIT_READINGS;
DROP TABLE dbresprod.dbo.MONNIT_DATA_TYPES;
DROP TABLE dbresprod.dbo.MONNIT_PLOT_LABELS;
DROP TABLE dbresprod.dbo.MONNIT_SENSORS;
DROP TABLE dbresprod.dbo.MONNIT_NETWORKS;
DROP TABLE dbresprod.dbo.MONNIT_APPLICATIONS;
GO