/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

/* */
CREATE PROCEDURE PROC_GET_OR_CREATE_TTN_ ()

