/* Drop existing TTN tables from the DB */ 
DROP TABLE dbresprod.dbo.TTN_UPLINK_SETTINGS
DROP TABLE dbresprod.dbo.TTN_READINGS
DROP TABLE dbresprod.dbo.TTN_UPLINK_TOKENS
DROP TABLE dbresprod.dbo.TTN_CORRELATION_IDS
DROP TABLE dbresprod.dbo.TTN_DATETIMES
DROP TABLE dbresprod.dbo.TTN_HOPS
DROP TABLE dbresprod.dbo.TTN_RX
DROP TABLE dbresprod.dbo.TTN_UPLINKS
DROP TABLE dbresprod.dbo.TTN_DEVICES
DROP TABLE dbresprod.dbo.TTN_SENSORS
DROP TABLE dbresprod.dbo.TTN_GATEWAYS
DROP TABLE dbresprod.dbo.TTN_LOCATIONS
DROP TABLE dbresprod.dbo.TTN_WARNINGS
DROP TABLE dbresprod.dbo.TTN_APPLICATIONS
GO
